target("common_macros")
    set_kind("headeronly")
    add_headerfiles("macros.hpp")
target_end()

target("common_logging")
    set_kind("headeronly")
    add_headerfiles("logging.hpp")
    add_packages("spdlog", {public = true})
    add_defines("SPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE", {public = true})
target_end()

target("common_exec_on_exit")
    set_kind("headeronly")
    add_headerfiles("exec_on_exit.hpp")
target_end()

target("common_chrono_inspector")
    set_kind("headeronly")
    add_headerfiles("chrono_inspector.hpp")
    add_deps("common_logging")
target_end()

target("common_aligned_allocator")
    set_kind("headeronly")
    add_headerfiles("aligned_allocator.hpp")
target_end()

target("common_aligned_memory_resource")
    set_kind("headeronly")
    add_headerfiles("aligned_memory_resource.hpp")
    add_packages("boost", {public = true})
target_end()

target("common_in_in_in_out_result")
    set_kind("headeronly")
    add_headerfiles("in_in_in_out_result.hpp")
target_end()
