target("bicycle_feedforward_controller")
    set_kind("headeronly")
    add_headerfiles("feedforward_controller.hpp")
target_end()

target("bicycle_pid_controller")
    set_kind("headeronly")
    add_headerfiles("pid_controller.hpp")
target_end()

target("bicycle_model_predictive_controller")
    set_kind("headeronly")
    add_headerfiles("model_predictive_controller.hpp")
target_end()

target("bicycle_kinematics_flow_controller")
    set_kind("headeronly")
    add_headerfiles("kinematics_flow_controller.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("bicycle_kinematics_model", "bicycle_state")
target_end()
