target("bicycle_route_line_cubic_acc_planner_test")
    add_rules("boyle.cxx.test")
    add_files("route_line_cubic_acc_planner_test.cpp")
    add_deps("bicycle_route_line_cubic_acc_planner")
target_end()

target("bicycle_route_line_quintic_acc_planner_test")
    add_rules("boyle.cxx.test")
    add_files("route_line_quintic_acc_planner_test.cpp")
    add_deps("bicycle_route_line_quintic_acc_planner")
target_end()

target("bicycle_route_line_cubic_offset_planner_test")
    add_rules("boyle.cxx.test")
    add_files("route_line_cubic_offset_planner_test.cpp")
    add_deps("bicycle_route_line_cubic_offset_planner")
target_end()

target("bicycle_route_line_quintic_offset_planner_test")
    add_rules("boyle.cxx.test")
    add_files("route_line_quintic_offset_planner_test.cpp")
    add_deps("bicycle_route_line_quintic_offset_planner")
target_end()

target("bicycle_route_line_kinematics_planner_test")
    add_rules("boyle.cxx.test")
    add_files("route_line_kinematics_planner_test.cpp")
    add_deps("bicycle_route_line_kinematics_planner")
target_end()
