target("bicycle_dualism")
    set_kind("headeronly")
    add_headerfiles("dualism.hpp")
target_end()

target("bicycle_route_line")
    set_kind("headeronly")
    add_headerfiles("route_line.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_piecewise_quintic_curve", "math_utils", "math_vec2")
target_end()

target("bicycle_path")
    set_kind("headeronly")
    add_headerfiles("path.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_piecewise_quintic_curve", "math_utils", "math_vec2")
target_end()

target("bicycle_motion")
    set_kind("headeronly")
    add_headerfiles("motion.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_concepts", "math_vec2", "math_piecewise_quintic_function")
target_end()

target("bicycle_fence")
    set_kind("headeronly")
    add_headerfiles("fence.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("bicycle_dualism", "math_concepts", "math_vec2", "math_piecewise_linear_function")
target_end()

target("bicycle_border")
    set_kind("headeronly")
    add_headerfiles("border.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("bicycle_dualism", "math_concepts", "math_piecewise_linear_curve", "math_vec2")
target_end()

target("bicycle_route_line_cubic_acc_planner")
    set_kind("headeronly")
    add_headerfiles("route_line_cubic_acc_planner.hpp")
    add_deps("common_logging", "cvxopm_osqp_problem", "cvxopm_osqp_solver", "bicycle_motion", "bicycle_fence")
target_end()

target("bicycle_route_line_quintic_acc_planner")
    set_kind("headeronly")
    add_headerfiles("route_line_quintic_acc_planner.hpp")
    add_deps("common_logging", "cvxopm_osqp_problem", "cvxopm_osqp_solver", "bicycle_motion", "bicycle_fence")
target_end()

target("bicycle_route_line_cubic_offset_planner")
    set_kind("headeronly")
    add_headerfiles("route_line_cubic_offset_planner.hpp")
    add_deps("common_logging", "math_piecewise_cubic_curve", "cvxopm_osqp_problem", "cvxopm_osqp_solver", "bicycle_path", "bicycle_border")
target_end()

target("bicycle_route_line_quintic_offset_planner")
    set_kind("headeronly")
    add_headerfiles("route_line_quintic_offset_planner.hpp")
    add_deps("common_logging", "math_piecewise_quintic_curve", "cvxopm_osqp_problem", "cvxopm_osqp_solver", "bicycle_path", "bicycle_border")
target_end()

target("bicycle_route_line_kinematics_planner")
    set_kind("headeronly")
    add_headerfiles("route_line_kinematics_planner.hpp")
target_end()
