target("math_mdfunction_proxy")
    set_kind("headeronly")
    add_headerfiles("mdfunction_proxy.hpp")
    add_packages("msft_proxy4", "zpp_bits", {public = true})
    add_deps("math_matrixx", "math_linear_mdfunction", "math_quadratic_mdfunction", "math_rosenbrock_function")
target_end()

target("math_linear_mdfunction")
    set_kind("headeronly")
    add_headerfiles("linear_mdfunction.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_concepts")
target_end()

target("math_quadratic_mdfunction")
    set_kind("headeronly")
    add_headerfiles("quadratic_mdfunction.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_concepts")
target_end()

target("math_rosenbrock_function")
    set_kind("headeronly")
    add_headerfiles("rosenbrock_function.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("math_concepts")
target_end()
