target("math_function_proxy")
    set_kind("headeronly")
    add_headerfiles("function_proxy.hpp")
    add_packages("msft_proxy4", "zpp_bits", {public = true})
    add_deps("math_concepts", "math_piecewise_linear_function", "math_piecewise_cubic_function", "math_piecewise_quintic_function")
target_end()

target("math_piecewise_linear_function")
    set_kind("headeronly")
    add_headerfiles("piecewise_linear_function.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("common_aligned_allocator", "math_concepts", "math_utils", "math_vec2", "math_vec3", "math_vector", "math_vectorx")
target_end()

target("math_piecewise_cubic_function")
    set_kind("headeronly")
    add_headerfiles("piecewise_cubic_function.hpp", "boundary_mode.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("common_aligned_allocator", "math_concepts", "math_cubic_interpolation", "math_utils", "math_vec2", "math_vec3", "math_vector", "math_vectorx")
target_end()

target("math_piecewise_quintic_function")
    set_kind("headeronly")
    add_headerfiles("piecewise_quintic_function.hpp", "boundary_mode.hpp")
    add_packages("zpp_bits", {public = true})
    add_deps("common_aligned_allocator", "math_concepts", "math_quintic_interpolation", "math_utils", "math_vec2", "math_vec3", "math_vector", "math_vectorx")
target_end()
